# Generated by Django 6.0.7 on 2026-07-27 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.TextField()),
                ('fecha_ingreso_paciente', models.DateTimeField()),
                ('fecha_salida_paciente', models.DateTimeField(blank=True, null=True)),
                ('tipo_autorizacion_salida', models.CharField(blank=True, choices=[('medico', 'Médico'), ('paciente', 'Paciente'), ('acompanante', 'Acompañante / familiar')], max_length=20)),
            ],
            options={
                'verbose_name': 'historia clínica',
                'verbose_name_plural': 'historias clínicas',
                'ordering': ['-fecha_ingreso_paciente'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_iso', models.CharField(blank=True, max_length=3, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(choices=[('admin', 'Admin'), ('cliente_paciente', 'Cliente / paciente'), ('empresa', 'Empresa'), ('administrativo', 'Administrativo')], max_length=20)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'tipo de sangre',
                'verbose_name_plural': 'tipos de sangre',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaisCiudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.ciudad')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.pais')),
            ],
            options={
                'verbose_name': 'país-ciudad',
                'verbose_name_plural': 'país-ciudad',
                'unique_together': {('pais', 'ciudad')},
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='paises',
            field=models.ManyToManyField(related_name='ciudades', through='personas.PaisCiudad', to='personas.pais'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('edad', models.PositiveSmallIntegerField()),
                ('telefono_personal', models.CharField(blank=True, max_length=20)),
                ('telefono_acompanante', models.CharField(blank=True, max_length=20, verbose_name='teléfono acompañante')),
                ('correo', models.EmailField(max_length=254)),
                ('ciudad_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_nacidas', to='personas.ciudad')),
                ('pais_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_nacidas', to='personas.pais')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinicaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_historia', models.CharField(choices=[('paciente', 'Paciente'), ('medico_tratante', 'Médico tratante'), ('acompanante', 'Acompañante / familiar')], max_length=20)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.historiaclinica')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
            options={
                'verbose_name': 'persona en historia clínica',
                'verbose_name_plural': 'personas en historia clínica',
                'unique_together': {('historia_clinica', 'persona', 'rol_en_historia')},
            },
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_realizadas', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='personas',
            field=models.ManyToManyField(related_name='historias_clinicas', through='personas.HistoriaClinicaPersona', to='personas.persona'),
        ),
        migrations.CreateModel(
            name='RolPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.rol')),
            ],
            options={
                'verbose_name': 'rol de persona',
                'verbose_name_plural': 'roles de persona',
                'unique_together': {('persona', 'rol')},
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='roles',
            field=models.ManyToManyField(related_name='personas', through='personas.RolPersona', to='personas.rol'),
        ),
        migrations.CreateModel(
            name='TipoSangrePersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
                ('tipo_sangre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.tiposangre')),
            ],
            options={
                'verbose_name': 'tipo de sangre de persona',
                'verbose_name_plural': 'tipos de sangre de persona',
                'unique_together': {('persona', 'tipo_sangre')},
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='tipos_sangre',
            field=models.ManyToManyField(related_name='personas', through='personas.TipoSangrePersona', to='personas.tiposangre'),
        ),
    ]
