# Generated by Django 6.0.7 on 2026-07-27 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_seed_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='persona_contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacto_de_historias', to='personas.persona', verbose_name='persona de contacto / acompañante'),
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personales_patologicos', models.TextField(blank=True, help_text='Enfermedades previas, cirugías, hospitalizaciones', verbose_name='antecedentes personales patológicos')),
                ('familiares', models.TextField(blank=True, help_text='Enfermedades hereditarias o frecuentes en la familia', verbose_name='antecedentes familiares')),
                ('no_patologicos', models.TextField(blank=True, help_text='Hábitos: alimentación, ejercicio, consumo de sustancias, vacunas', verbose_name='antecedentes no patológicos')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedente', to='personas.historiaclinica')),
            ],
            options={
                'verbose_name': 'antecedente',
                'verbose_name_plural': 'antecedentes',
            },
        ),
        migrations.CreateModel(
            name='DatosAdministrativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_atencion', models.DateTimeField()),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_administrativos', to='personas.historiaclinica')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones_realizadas', to='personas.persona', verbose_name='profesional de la salud')),
            ],
            options={
                'verbose_name': 'datos administrativos',
                'verbose_name_plural': 'datos administrativos',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impresion_diagnostica', models.TextField(blank=True, help_text='Hipótesis inicial')),
                ('diagnostico_confirmado', models.TextField(blank=True)),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='personas.historiaclinica')),
            ],
            options={
                'verbose_name': 'diagnóstico',
                'verbose_name_plural': 'diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='ExamenComplementario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Laboratorio, imagen diagnóstica, prueba especial', max_length=100)),
                ('resultado', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_complementarios', to='personas.historiaclinica')),
            ],
            options={
                'verbose_name': 'examen complementario',
                'verbose_name_plural': 'exámenes complementarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_arterial', models.CharField(blank=True, max_length=20)),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frecuencia_respiratoria', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('evaluacion_por_sistemas', models.TextField(blank=True, help_text='Respiratorio, cardiovascular, digestivo, neurológico, etc.')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_fisico', to='personas.historiaclinica')),
            ],
            options={
                'verbose_name': 'examen físico',
                'verbose_name_plural': 'exámenes físicos',
            },
        ),
        migrations.CreateModel(
            name='HistoriaEnfermedadActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_cronologica', models.TextField(blank=True, help_text='Descripción cronológica de los síntomas')),
                ('factores_desencadenantes', models.TextField(blank=True, help_text='Factores desencadenantes o agravantes')),
                ('tratamientos_previos', models.TextField(blank=True)),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedad_actual', to='personas.historiaclinica')),
            ],
            options={
                'verbose_name': 'historia de la enfermedad actual',
                'verbose_name_plural': 'historias de la enfermedad actual',
            },
        ),
        migrations.CreateModel(
            name='MotivoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Razón principal por la que el paciente acude (dolor, control, chequeo, etc.)')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motivo_consulta', to='personas.historiaclinica')),
            ],
            options={
                'verbose_name': 'motivo de consulta',
                'verbose_name_plural': 'motivos de consulta',
            },
        ),
        migrations.CreateModel(
            name='PlanManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento_indicado', models.TextField(blank=True, help_text='Medicamentos, terapias, procedimientos')),
                ('recomendaciones', models.TextField(blank=True)),
                ('fecha_proxima_cita', models.DateField(blank=True, null=True)),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_de_manejo', to='personas.historiaclinica')),
            ],
            options={
                'verbose_name': 'plan de manejo',
                'verbose_name_plural': 'planes de manejo',
            },
        ),
    ]
