# Generated by Django 6.0.7 on 2026-08-12 23:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_rol_guardia_jornada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=50, verbose_name='NIT')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('especialidad', models.CharField(max_length=150, verbose_name='Especialidad / Servicio')),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'db_table': 'convenio',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
