# Generated by Django 6.0.7 on 2026-08-25 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0012_receta_itemreceta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRegistroPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
                ('persona_creada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='personas.persona')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_registro_hechas', to='personas.persona')),
            ],
            options={
                'verbose_name': 'solicitud de registro de paciente',
                'verbose_name_plural': 'solicitudes de registro de paciente',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
