# Generated by Django 6.0.7 on 2026-08-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0013_solicitudregistropaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('RC', 'Registro civil'), ('PA', 'Pasaporte')], default='CC', max_length=2),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='cédula / documento'),
        ),
    ]
