# Generated by Django 6.0.7 on 2026-08-25 23:02

from django.db import migrations, models


def fijar_categorias(apps, schema_editor):
    """Gerente y Recepcionista dejan de ser sub-roles de la categoria
    'administrativo' (que desaparece) y pasan a ser categorias propias,
    mismo nivel que Médico/Enfermera -- Rol.nombre='gerente'/'recepcionista'
    quedaban con categoria='administrativo', ahora un valor inválido."""
    Rol = apps.get_model('personas', 'Rol')
    Rol.objects.filter(nombre='gerente').update(categoria='gerente')
    Rol.objects.filter(nombre='recepcionista').update(categoria='recepcionista')


def revertir_categorias(apps, schema_editor):
    Rol = apps.get_model('personas', 'Rol')
    Rol.objects.filter(nombre='gerente').update(categoria='administrativo')
    Rol.objects.filter(nombre='recepcionista').update(categoria='administrativo')


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0014_persona_tipo_documento_alter_persona_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='categoria',
            field=models.CharField(choices=[('admin', 'Admin'), ('cliente_paciente', 'Cliente / paciente'), ('empresa', 'Empresa'), ('gerente', 'Gerente'), ('recepcionista', 'Recepcionista'), ('medico', 'Médico'), ('enfermera', 'Enfermera'), ('guardia', 'Guardia de seguridad')], max_length=20),
        ),
        migrations.RunPython(fijar_categorias, revertir_categorias),
    ]
