# Generated by Django 6.0.7 on 2026-08-26 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0015_alter_rol_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistropaciente',
            name='atendida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_registro_atendidas', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='solicitudregistropaciente',
            name='fecha_atendida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
