# Generated by Django 6.0.7 on 2026-08-26 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0016_solicitudregistropaciente_atendida_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_realizados', to='personas.persona', verbose_name='registrado por'),
        ),
    ]
