# Generated by Django 6.0.7 on 2026-07-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0005_solo_colombia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='pendiente', max_length=20)),
                ('motivo', models.CharField(help_text='Consulta general, control, examen, etc.', max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_como_medico', to='personas.persona')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_paciente', to='personas.persona')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='CitaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('reservar', 'Reservar'), ('cancelar', 'Cancelar'), ('reprogramar', 'Reprogramar')], max_length=20)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='citas.cita')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_citas', to='personas.persona')),
            ],
            options={
                'verbose_name': 'historial de cita',
                'verbose_name_plural': 'historial de citas',
                'ordering': ['-fecha_accion'],
            },
        ),
    ]
