# Generated by Django 6.0.7 on 2026-08-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cita_estado_atendida_historia_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citahistorial',
            name='accion',
            field=models.CharField(choices=[('reservar', 'Reservar'), ('cancelar', 'Cancelar'), ('reprogramar', 'Reprogramar'), ('asignar', 'Asignar médico')], max_length=20),
        ),
    ]
