--
-- PostgreSQL database dump
--

\restrict eyxS6CYvgGnQEPbB8mCdAei7GWTdCflfrx5smzMl2aEsYwdi7tUCRRojY7vg6P7

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: citas_cita; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.citas_cita (
    id bigint NOT NULL,
    fecha_hora timestamp with time zone NOT NULL,
    estado character varying(20) NOT NULL,
    motivo character varying(200) NOT NULL,
    observaciones text NOT NULL,
    medico_id bigint,
    persona_id bigint NOT NULL
);


--
-- Name: citas_cita_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.citas_cita ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.citas_cita_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: citas_citahistorial; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.citas_citahistorial (
    id bigint NOT NULL,
    accion character varying(20) NOT NULL,
    fecha_accion timestamp with time zone NOT NULL,
    comentario text NOT NULL,
    cita_id bigint NOT NULL,
    usuario_responsable_id bigint
);


--
-- Name: citas_citahistorial_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.citas_citahistorial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.citas_citahistorial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: personas_antecedente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_antecedente (
    id bigint NOT NULL,
    personales_patologicos text NOT NULL,
    familiares text NOT NULL,
    no_patologicos text NOT NULL,
    historia_clinica_id bigint NOT NULL
);


--
-- Name: personas_antecedente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_antecedente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_antecedente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_ciudad; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_ciudad (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


--
-- Name: personas_ciudad_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_ciudad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_ciudad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_datosadministrativos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_datosadministrativos (
    id bigint NOT NULL,
    fecha_hora_atencion timestamp with time zone NOT NULL,
    historia_clinica_id bigint NOT NULL,
    profesional_id bigint
);


--
-- Name: personas_datosadministrativos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_datosadministrativos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_datosadministrativos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_diagnostico; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_diagnostico (
    id bigint NOT NULL,
    impresion_diagnostica text NOT NULL,
    diagnostico_confirmado text NOT NULL,
    historia_clinica_id bigint NOT NULL
);


--
-- Name: personas_diagnostico_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_diagnostico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_diagnostico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_examencomplementario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_examencomplementario (
    id bigint NOT NULL,
    tipo character varying(100) NOT NULL,
    resultado text NOT NULL,
    fecha date NOT NULL,
    historia_clinica_id bigint NOT NULL
);


--
-- Name: personas_examencomplementario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_examencomplementario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_examencomplementario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_examenfisico; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_examenfisico (
    id bigint NOT NULL,
    presion_arterial character varying(20) NOT NULL,
    frecuencia_cardiaca smallint,
    temperatura numeric(4,1),
    frecuencia_respiratoria smallint,
    evaluacion_por_sistemas text NOT NULL,
    historia_clinica_id bigint NOT NULL,
    CONSTRAINT personas_examenfisico_frecuencia_cardiaca_check CHECK ((frecuencia_cardiaca >= 0)),
    CONSTRAINT personas_examenfisico_frecuencia_respiratoria_check CHECK ((frecuencia_respiratoria >= 0))
);


--
-- Name: personas_examenfisico_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_examenfisico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_examenfisico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_historiaclinica; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_historiaclinica (
    id bigint NOT NULL,
    tratamiento text NOT NULL,
    fecha_ingreso_paciente timestamp with time zone NOT NULL,
    fecha_salida_paciente timestamp with time zone,
    tipo_autorizacion_salida character varying(20) NOT NULL,
    autorizado_por_id bigint,
    ocupacion character varying(100) NOT NULL,
    persona_contacto_id bigint
);


--
-- Name: personas_historiaclinica_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_historiaclinica ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_historiaclinica_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_historiaclinicapersona; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_historiaclinicapersona (
    id bigint NOT NULL,
    rol_en_historia character varying(20) NOT NULL,
    historia_clinica_id bigint NOT NULL,
    persona_id bigint NOT NULL
);


--
-- Name: personas_historiaclinicapersona_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_historiaclinicapersona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_historiaclinicapersona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_historiaenfermedadactual; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_historiaenfermedadactual (
    id bigint NOT NULL,
    descripcion_cronologica text CONSTRAINT personas_historiaenfermedadact_descripcion_cronologica_not_null NOT NULL,
    factores_desencadenantes text CONSTRAINT personas_historiaenfermedadac_factores_desencadenantes_not_null NOT NULL,
    tratamientos_previos text NOT NULL,
    historia_clinica_id bigint NOT NULL
);


--
-- Name: personas_historiaenfermedadactual_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_historiaenfermedadactual ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_historiaenfermedadactual_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_motivoconsulta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_motivoconsulta (
    id bigint NOT NULL,
    descripcion text NOT NULL,
    historia_clinica_id bigint NOT NULL
);


--
-- Name: personas_motivoconsulta_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_motivoconsulta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_motivoconsulta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_pais; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_pais (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    codigo_iso character varying(3)
);


--
-- Name: personas_pais_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_pais ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_pais_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_paisciudad; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_paisciudad (
    id bigint NOT NULL,
    ciudad_id bigint NOT NULL,
    pais_id bigint NOT NULL
);


--
-- Name: personas_paisciudad_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_paisciudad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_paisciudad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_persona; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_persona (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    apellido character varying(100) NOT NULL,
    cedula character varying(20) NOT NULL,
    edad smallint NOT NULL,
    telefono_personal character varying(20) NOT NULL,
    telefono_acompanante character varying(20) NOT NULL,
    correo character varying(254) NOT NULL,
    ciudad_nacimiento_id bigint,
    pais_nacimiento_id bigint,
    usuario_id integer,
    direccion character varying(255) NOT NULL,
    sexo character varying(1) NOT NULL,
    CONSTRAINT personas_persona_edad_check CHECK ((edad >= 0))
);


--
-- Name: personas_persona_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_persona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_persona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_planmanejo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_planmanejo (
    id bigint NOT NULL,
    tratamiento_indicado text NOT NULL,
    recomendaciones text NOT NULL,
    fecha_proxima_cita date,
    historia_clinica_id bigint NOT NULL
);


--
-- Name: personas_planmanejo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_planmanejo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_planmanejo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_rol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_rol (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    categoria character varying(20) NOT NULL
);


--
-- Name: personas_rol_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_rolpersona; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_rolpersona (
    id bigint NOT NULL,
    fecha_asignacion timestamp with time zone NOT NULL,
    persona_id bigint NOT NULL,
    rol_id bigint NOT NULL
);


--
-- Name: personas_rolpersona_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_rolpersona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_rolpersona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_tiposangre; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_tiposangre (
    id bigint NOT NULL,
    nombre character varying(3) NOT NULL
);


--
-- Name: personas_tiposangre_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_tiposangre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_tiposangre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas_tiposangrepersona; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_tiposangrepersona (
    id bigint NOT NULL,
    persona_id bigint NOT NULL,
    tipo_sangre_id bigint NOT NULL
);


--
-- Name: personas_tiposangrepersona_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas_tiposangrepersona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_tiposangrepersona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add ciudad	7	add_ciudad
26	Can change ciudad	7	change_ciudad
27	Can delete ciudad	7	delete_ciudad
28	Can view ciudad	7	view_ciudad
29	Can add historia clínica	8	add_historiaclinica
30	Can change historia clínica	8	change_historiaclinica
31	Can delete historia clínica	8	delete_historiaclinica
32	Can view historia clínica	8	view_historiaclinica
33	Can add país	10	add_pais
34	Can change país	10	change_pais
35	Can delete país	10	delete_pais
36	Can view país	10	view_pais
37	Can add rol	13	add_rol
38	Can change rol	13	change_rol
39	Can delete rol	13	delete_rol
40	Can view rol	13	view_rol
41	Can add tipo de sangre	15	add_tiposangre
42	Can change tipo de sangre	15	change_tiposangre
43	Can delete tipo de sangre	15	delete_tiposangre
44	Can view tipo de sangre	15	view_tiposangre
45	Can add país-ciudad	11	add_paisciudad
46	Can change país-ciudad	11	change_paisciudad
47	Can delete país-ciudad	11	delete_paisciudad
48	Can view país-ciudad	11	view_paisciudad
49	Can add persona	12	add_persona
50	Can change persona	12	change_persona
51	Can delete persona	12	delete_persona
52	Can view persona	12	view_persona
53	Can add persona en historia clínica	9	add_historiaclinicapersona
54	Can change persona en historia clínica	9	change_historiaclinicapersona
55	Can delete persona en historia clínica	9	delete_historiaclinicapersona
56	Can view persona en historia clínica	9	view_historiaclinicapersona
57	Can add rol de persona	14	add_rolpersona
58	Can change rol de persona	14	change_rolpersona
59	Can delete rol de persona	14	delete_rolpersona
60	Can view rol de persona	14	view_rolpersona
61	Can add tipo de sangre de persona	16	add_tiposangrepersona
62	Can change tipo de sangre de persona	16	change_tiposangrepersona
63	Can delete tipo de sangre de persona	16	delete_tiposangrepersona
64	Can view tipo de sangre de persona	16	view_tiposangrepersona
65	Can add antecedente	17	add_antecedente
66	Can change antecedente	17	change_antecedente
67	Can delete antecedente	17	delete_antecedente
68	Can view antecedente	17	view_antecedente
69	Can add datos administrativos	18	add_datosadministrativos
70	Can change datos administrativos	18	change_datosadministrativos
71	Can delete datos administrativos	18	delete_datosadministrativos
72	Can view datos administrativos	18	view_datosadministrativos
73	Can add diagnóstico	19	add_diagnostico
74	Can change diagnóstico	19	change_diagnostico
75	Can delete diagnóstico	19	delete_diagnostico
76	Can view diagnóstico	19	view_diagnostico
77	Can add examen complementario	20	add_examencomplementario
78	Can change examen complementario	20	change_examencomplementario
79	Can delete examen complementario	20	delete_examencomplementario
80	Can view examen complementario	20	view_examencomplementario
81	Can add examen físico	21	add_examenfisico
82	Can change examen físico	21	change_examenfisico
83	Can delete examen físico	21	delete_examenfisico
84	Can view examen físico	21	view_examenfisico
85	Can add historia de la enfermedad actual	22	add_historiaenfermedadactual
86	Can change historia de la enfermedad actual	22	change_historiaenfermedadactual
87	Can delete historia de la enfermedad actual	22	delete_historiaenfermedadactual
88	Can view historia de la enfermedad actual	22	view_historiaenfermedadactual
89	Can add motivo de consulta	23	add_motivoconsulta
90	Can change motivo de consulta	23	change_motivoconsulta
91	Can delete motivo de consulta	23	delete_motivoconsulta
92	Can view motivo de consulta	23	view_motivoconsulta
93	Can add plan de manejo	24	add_planmanejo
94	Can change plan de manejo	24	change_planmanejo
95	Can delete plan de manejo	24	delete_planmanejo
96	Can view plan de manejo	24	view_planmanejo
97	Can add cita	25	add_cita
98	Can change cita	25	change_cita
99	Can delete cita	25	delete_cita
100	Can view cita	25	view_cita
101	Can add historial de cita	26	add_citahistorial
102	Can change historial de cita	26	change_citahistorial
103	Can delete historial de cita	26	delete_citahistorial
104	Can view historial de cita	26	view_citahistorial
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$76YtjGSC6XPjAFOPt66Qcc$UAys/9FiaDTfh76ACb6EHUB4pyZmdaEUpmnF2JdI59I=	2026-07-27 11:12:13.569015-05	t	admin			admin@pulsesas.local	t	t	2026-07-27 10:51:51.691115-05
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: citas_cita; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.citas_cita (id, fecha_hora, estado, motivo, observaciones, medico_id, persona_id) FROM stdin;
\.


--
-- Data for Name: citas_citahistorial; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.citas_citahistorial (id, accion, fecha_accion, comentario, cita_id, usuario_responsable_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	personas	ciudad
8	personas	historiaclinica
9	personas	historiaclinicapersona
10	personas	pais
11	personas	paisciudad
12	personas	persona
13	personas	rol
14	personas	rolpersona
15	personas	tiposangre
16	personas	tiposangrepersona
17	personas	antecedente
18	personas	datosadministrativos
19	personas	diagnostico
20	personas	examencomplementario
21	personas	examenfisico
22	personas	historiaenfermedadactual
23	personas	motivoconsulta
24	personas	planmanejo
25	citas	cita
26	citas	citahistorial
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-07-27 10:48:06.821308-05
2	auth	0001_initial	2026-07-27 10:48:06.997162-05
3	admin	0001_initial	2026-07-27 10:48:07.028921-05
4	admin	0002_logentry_remove_auto_add	2026-07-27 10:48:07.035567-05
5	admin	0003_logentry_add_action_flag_choices	2026-07-27 10:48:07.043133-05
6	contenttypes	0002_remove_content_type_name	2026-07-27 10:48:07.055524-05
7	auth	0002_alter_permission_name_max_length	2026-07-27 10:48:07.063862-05
8	auth	0003_alter_user_email_max_length	2026-07-27 10:48:07.071731-05
9	auth	0004_alter_user_username_opts	2026-07-27 10:48:07.078889-05
10	auth	0005_alter_user_last_login_null	2026-07-27 10:48:07.087416-05
11	auth	0006_require_contenttypes_0002	2026-07-27 10:48:07.089613-05
12	auth	0007_alter_validators_add_error_messages	2026-07-27 10:48:07.094915-05
13	auth	0008_alter_user_username_max_length	2026-07-27 10:48:07.106964-05
14	auth	0009_alter_user_last_name_max_length	2026-07-27 10:48:07.114716-05
15	auth	0010_alter_group_name_max_length	2026-07-27 10:48:07.122373-05
16	auth	0011_update_proxy_permissions	2026-07-27 10:48:07.128977-05
17	auth	0012_alter_user_first_name_max_length	2026-07-27 10:48:07.134778-05
18	personas	0001_initial	2026-07-27 10:48:07.383654-05
19	personas	0002_seed_datos	2026-07-27 10:48:07.710383-05
20	sessions	0001_initial	2026-07-27 10:48:07.727886-05
21	personas	0003_historiaclinica_ocupacion_and_more	2026-07-27 11:16:38.761486-05
22	personas	0004_seed_capitales	2026-07-27 11:16:39.930748-05
23	personas	0005_solo_colombia	2026-07-27 11:17:30.070745-05
24	citas	0001_initial	2026-07-27 11:23:51.355583-05
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
kd42fdzjt5ie987rltjaqduijfayon75	.eJxVjEsOgjAUAO_y1qaRV_qBpXvOQN6ntaiBhMLKeHdDwkK3M5N5w0j7Vsa9pnWcFHpo4PLLmOSZ5kPog-b7YmSZt3VicyTmtNUMi6bX7Wz_BoVqgR5iQN8ii7PqbEAV8cyJExM3nKMj0abz2Ga-OhFBppiDWNd5wUya4fMFCPY5dQ:1woNw5:7if7RjTsUbRtTe_uwsrhr89MiYeWcuX873P9mhqRatA	2026-08-10 11:12:13.571748-05
\.


--
-- Data for Name: personas_antecedente; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_antecedente (id, personales_patologicos, familiares, no_patologicos, historia_clinica_id) FROM stdin;
\.


--
-- Data for Name: personas_ciudad; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_ciudad (id, nombre) FROM stdin;
197	Bogotá
198	Medellín
199	Cali
200	Barranquilla
201	Cartagena de Indias
202	Cúcuta
203	Bucaramanga
204	Pereira
205	Santa Marta
206	Ibagué
207	Pasto
208	Manizales
209	Neiva
210	Villavicencio
211	Armenia
212	Valledupar
213	Montería
214	Sincelejo
215	Popayán
216	Tunja
217	Riohacha
218	Quibdó
219	Florencia
220	Yopal
221	Arauca
222	Mocoa
223	San José del Guaviare
224	Mitú
225	Puerto Carreño
226	Inírida
227	Leticia
228	San Andrés
\.


--
-- Data for Name: personas_datosadministrativos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_datosadministrativos (id, fecha_hora_atencion, historia_clinica_id, profesional_id) FROM stdin;
\.


--
-- Data for Name: personas_diagnostico; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_diagnostico (id, impresion_diagnostica, diagnostico_confirmado, historia_clinica_id) FROM stdin;
\.


--
-- Data for Name: personas_examencomplementario; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_examencomplementario (id, tipo, resultado, fecha, historia_clinica_id) FROM stdin;
\.


--
-- Data for Name: personas_examenfisico; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_examenfisico (id, presion_arterial, frecuencia_cardiaca, temperatura, frecuencia_respiratoria, evaluacion_por_sistemas, historia_clinica_id) FROM stdin;
\.


--
-- Data for Name: personas_historiaclinica; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_historiaclinica (id, tratamiento, fecha_ingreso_paciente, fecha_salida_paciente, tipo_autorizacion_salida, autorizado_por_id, ocupacion, persona_contacto_id) FROM stdin;
\.


--
-- Data for Name: personas_historiaclinicapersona; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_historiaclinicapersona (id, rol_en_historia, historia_clinica_id, persona_id) FROM stdin;
\.


--
-- Data for Name: personas_historiaenfermedadactual; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_historiaenfermedadactual (id, descripcion_cronologica, factores_desencadenantes, tratamientos_previos, historia_clinica_id) FROM stdin;
\.


--
-- Data for Name: personas_motivoconsulta; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_motivoconsulta (id, descripcion, historia_clinica_id) FROM stdin;
\.


--
-- Data for Name: personas_pais; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_pais (id, nombre, codigo_iso) FROM stdin;
42	Colombia	CO
\.


--
-- Data for Name: personas_paisciudad; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_paisciudad (id, ciudad_id, pais_id) FROM stdin;
197	197	42
198	198	42
199	199	42
200	200	42
201	201	42
202	202	42
203	203	42
204	204	42
205	205	42
206	206	42
207	207	42
208	208	42
209	209	42
210	210	42
211	211	42
212	212	42
213	213	42
214	214	42
215	215	42
216	216	42
217	217	42
218	218	42
219	219	42
220	220	42
221	221	42
222	222	42
223	223	42
224	224	42
225	225	42
226	226	42
227	227	42
228	228	42
\.


--
-- Data for Name: personas_persona; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_persona (id, nombre, apellido, cedula, edad, telefono_personal, telefono_acompanante, correo, ciudad_nacimiento_id, pais_nacimiento_id, usuario_id, direccion, sexo) FROM stdin;
\.


--
-- Data for Name: personas_planmanejo; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_planmanejo (id, tratamiento_indicado, recomendaciones, fecha_proxima_cita, historia_clinica_id) FROM stdin;
\.


--
-- Data for Name: personas_rol; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_rol (id, nombre, categoria) FROM stdin;
1	admin	admin
2	cliente_paciente	cliente_paciente
3	empresa	empresa
4	gerente	administrativo
5	supervisor	administrativo
6	medico	administrativo
7	enfermera	administrativo
8	contadora	administrativo
9	recepcionista	administrativo
\.


--
-- Data for Name: personas_rolpersona; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_rolpersona (id, fecha_asignacion, persona_id, rol_id) FROM stdin;
\.


--
-- Data for Name: personas_tiposangre; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_tiposangre (id, nombre) FROM stdin;
1	A+
2	A-
3	B+
4	B-
5	AB+
6	AB-
7	O+
8	O-
\.


--
-- Data for Name: personas_tiposangrepersona; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.personas_tiposangrepersona (id, persona_id, tipo_sangre_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 104, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: citas_cita_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.citas_cita_id_seq', 1, false);


--
-- Name: citas_citahistorial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.citas_citahistorial_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 26, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 24, true);


--
-- Name: personas_antecedente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_antecedente_id_seq', 1, false);


--
-- Name: personas_ciudad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_ciudad_id_seq', 228, true);


--
-- Name: personas_datosadministrativos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_datosadministrativos_id_seq', 1, false);


--
-- Name: personas_diagnostico_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_diagnostico_id_seq', 1, false);


--
-- Name: personas_examencomplementario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_examencomplementario_id_seq', 1, false);


--
-- Name: personas_examenfisico_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_examenfisico_id_seq', 1, false);


--
-- Name: personas_historiaclinica_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_historiaclinica_id_seq', 1, false);


--
-- Name: personas_historiaclinicapersona_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_historiaclinicapersona_id_seq', 1, false);


--
-- Name: personas_historiaenfermedadactual_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_historiaenfermedadactual_id_seq', 1, false);


--
-- Name: personas_motivoconsulta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_motivoconsulta_id_seq', 1, false);


--
-- Name: personas_pais_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_pais_id_seq', 196, true);


--
-- Name: personas_paisciudad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_paisciudad_id_seq', 228, true);


--
-- Name: personas_persona_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_persona_id_seq', 1, false);


--
-- Name: personas_planmanejo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_planmanejo_id_seq', 1, false);


--
-- Name: personas_rol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_rol_id_seq', 9, true);


--
-- Name: personas_rolpersona_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_rolpersona_id_seq', 1, false);


--
-- Name: personas_tiposangre_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_tiposangre_id_seq', 8, true);


--
-- Name: personas_tiposangrepersona_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_tiposangrepersona_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: citas_cita citas_cita_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_cita
    ADD CONSTRAINT citas_cita_pkey PRIMARY KEY (id);


--
-- Name: citas_citahistorial citas_citahistorial_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_citahistorial
    ADD CONSTRAINT citas_citahistorial_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: personas_antecedente personas_antecedente_historia_clinica_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_antecedente
    ADD CONSTRAINT personas_antecedente_historia_clinica_id_key UNIQUE (historia_clinica_id);


--
-- Name: personas_antecedente personas_antecedente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_antecedente
    ADD CONSTRAINT personas_antecedente_pkey PRIMARY KEY (id);


--
-- Name: personas_ciudad personas_ciudad_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_ciudad
    ADD CONSTRAINT personas_ciudad_pkey PRIMARY KEY (id);


--
-- Name: personas_datosadministrativos personas_datosadministrativos_historia_clinica_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_datosadministrativos
    ADD CONSTRAINT personas_datosadministrativos_historia_clinica_id_key UNIQUE (historia_clinica_id);


--
-- Name: personas_datosadministrativos personas_datosadministrativos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_datosadministrativos
    ADD CONSTRAINT personas_datosadministrativos_pkey PRIMARY KEY (id);


--
-- Name: personas_diagnostico personas_diagnostico_historia_clinica_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_diagnostico
    ADD CONSTRAINT personas_diagnostico_historia_clinica_id_key UNIQUE (historia_clinica_id);


--
-- Name: personas_diagnostico personas_diagnostico_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_diagnostico
    ADD CONSTRAINT personas_diagnostico_pkey PRIMARY KEY (id);


--
-- Name: personas_examencomplementario personas_examencomplementario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_examencomplementario
    ADD CONSTRAINT personas_examencomplementario_pkey PRIMARY KEY (id);


--
-- Name: personas_examenfisico personas_examenfisico_historia_clinica_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_examenfisico
    ADD CONSTRAINT personas_examenfisico_historia_clinica_id_key UNIQUE (historia_clinica_id);


--
-- Name: personas_examenfisico personas_examenfisico_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_examenfisico
    ADD CONSTRAINT personas_examenfisico_pkey PRIMARY KEY (id);


--
-- Name: personas_historiaclinicapersona personas_historiaclinica_historia_clinica_id_pers_15f06017_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_historiaclinicapersona
    ADD CONSTRAINT personas_historiaclinica_historia_clinica_id_pers_15f06017_uniq UNIQUE (historia_clinica_id, persona_id, rol_en_historia);


--
-- Name: personas_historiaclinica personas_historiaclinica_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_historiaclinica
    ADD CONSTRAINT personas_historiaclinica_pkey PRIMARY KEY (id);


--
-- Name: personas_historiaclinicapersona personas_historiaclinicapersona_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_historiaclinicapersona
    ADD CONSTRAINT personas_historiaclinicapersona_pkey PRIMARY KEY (id);


--
-- Name: personas_historiaenfermedadactual personas_historiaenfermedadactual_historia_clinica_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_historiaenfermedadactual
    ADD CONSTRAINT personas_historiaenfermedadactual_historia_clinica_id_key UNIQUE (historia_clinica_id);


--
-- Name: personas_historiaenfermedadactual personas_historiaenfermedadactual_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_historiaenfermedadactual
    ADD CONSTRAINT personas_historiaenfermedadactual_pkey PRIMARY KEY (id);


--
-- Name: personas_motivoconsulta personas_motivoconsulta_historia_clinica_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_motivoconsulta
    ADD CONSTRAINT personas_motivoconsulta_historia_clinica_id_key UNIQUE (historia_clinica_id);


--
-- Name: personas_motivoconsulta personas_motivoconsulta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_motivoconsulta
    ADD CONSTRAINT personas_motivoconsulta_pkey PRIMARY KEY (id);


--
-- Name: personas_pais personas_pais_codigo_iso_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_pais
    ADD CONSTRAINT personas_pais_codigo_iso_key UNIQUE (codigo_iso);


--
-- Name: personas_pais personas_pais_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_pais
    ADD CONSTRAINT personas_pais_nombre_key UNIQUE (nombre);


--
-- Name: personas_pais personas_pais_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_pais
    ADD CONSTRAINT personas_pais_pkey PRIMARY KEY (id);


--
-- Name: personas_paisciudad personas_paisciudad_pais_id_ciudad_id_cdbb78d6_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_paisciudad
    ADD CONSTRAINT personas_paisciudad_pais_id_ciudad_id_cdbb78d6_uniq UNIQUE (pais_id, ciudad_id);


--
-- Name: personas_paisciudad personas_paisciudad_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_paisciudad
    ADD CONSTRAINT personas_paisciudad_pkey PRIMARY KEY (id);


--
-- Name: personas_persona personas_persona_cedula_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_persona
    ADD CONSTRAINT personas_persona_cedula_key UNIQUE (cedula);


--
-- Name: personas_persona personas_persona_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_persona
    ADD CONSTRAINT personas_persona_pkey PRIMARY KEY (id);


--
-- Name: personas_persona personas_persona_usuario_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_persona
    ADD CONSTRAINT personas_persona_usuario_id_key UNIQUE (usuario_id);


--
-- Name: personas_planmanejo personas_planmanejo_historia_clinica_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_planmanejo
    ADD CONSTRAINT personas_planmanejo_historia_clinica_id_key UNIQUE (historia_clinica_id);


--
-- Name: personas_planmanejo personas_planmanejo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_planmanejo
    ADD CONSTRAINT personas_planmanejo_pkey PRIMARY KEY (id);


--
-- Name: personas_rol personas_rol_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_rol
    ADD CONSTRAINT personas_rol_nombre_key UNIQUE (nombre);


--
-- Name: personas_rol personas_rol_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_rol
    ADD CONSTRAINT personas_rol_pkey PRIMARY KEY (id);


--
-- Name: personas_rolpersona personas_rolpersona_persona_id_rol_id_a7cde001_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_rolpersona
    ADD CONSTRAINT personas_rolpersona_persona_id_rol_id_a7cde001_uniq UNIQUE (persona_id, rol_id);


--
-- Name: personas_rolpersona personas_rolpersona_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_rolpersona
    ADD CONSTRAINT personas_rolpersona_pkey PRIMARY KEY (id);


--
-- Name: personas_tiposangre personas_tiposangre_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_tiposangre
    ADD CONSTRAINT personas_tiposangre_nombre_key UNIQUE (nombre);


--
-- Name: personas_tiposangre personas_tiposangre_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_tiposangre
    ADD CONSTRAINT personas_tiposangre_pkey PRIMARY KEY (id);


--
-- Name: personas_tiposangrepersona personas_tiposangreperso_persona_id_tipo_sangre_i_275433f8_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_tiposangrepersona
    ADD CONSTRAINT personas_tiposangreperso_persona_id_tipo_sangre_i_275433f8_uniq UNIQUE (persona_id, tipo_sangre_id);


--
-- Name: personas_tiposangrepersona personas_tiposangrepersona_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_tiposangrepersona
    ADD CONSTRAINT personas_tiposangrepersona_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: citas_cita_medico_id_aadcbe06; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_cita_medico_id_aadcbe06 ON public.citas_cita USING btree (medico_id);


--
-- Name: citas_cita_persona_id_5e7595f8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_cita_persona_id_5e7595f8 ON public.citas_cita USING btree (persona_id);


--
-- Name: citas_citahistorial_cita_id_a00066ef; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_citahistorial_cita_id_a00066ef ON public.citas_citahistorial USING btree (cita_id);


--
-- Name: citas_citahistorial_usuario_responsable_id_f8a5605b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_citahistorial_usuario_responsable_id_f8a5605b ON public.citas_citahistorial USING btree (usuario_responsable_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: personas_datosadministrativos_profesional_id_419644a4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_datosadministrativos_profesional_id_419644a4 ON public.personas_datosadministrativos USING btree (profesional_id);


--
-- Name: personas_examencomplementario_historia_clinica_id_7c7baaae; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_examencomplementario_historia_clinica_id_7c7baaae ON public.personas_examencomplementario USING btree (historia_clinica_id);


--
-- Name: personas_historiaclinica_autorizado_por_id_bc9a5f95; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_historiaclinica_autorizado_por_id_bc9a5f95 ON public.personas_historiaclinica USING btree (autorizado_por_id);


--
-- Name: personas_historiaclinica_persona_contacto_id_3d2bb551; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_historiaclinica_persona_contacto_id_3d2bb551 ON public.personas_historiaclinica USING btree (persona_contacto_id);


--
-- Name: personas_historiaclinicapersona_historia_clinica_id_a4d52dd3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_historiaclinicapersona_historia_clinica_id_a4d52dd3 ON public.personas_historiaclinicapersona USING btree (historia_clinica_id);


--
-- Name: personas_historiaclinicapersona_persona_id_cbdbbd03; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_historiaclinicapersona_persona_id_cbdbbd03 ON public.personas_historiaclinicapersona USING btree (persona_id);


--
-- Name: personas_pais_codigo_iso_0fc85366_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_pais_codigo_iso_0fc85366_like ON public.personas_pais USING btree (codigo_iso varchar_pattern_ops);


--
-- Name: personas_pais_nombre_1d1a5960_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_pais_nombre_1d1a5960_like ON public.personas_pais USING btree (nombre varchar_pattern_ops);


--
-- Name: personas_paisciudad_ciudad_id_44c1df30; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_paisciudad_ciudad_id_44c1df30 ON public.personas_paisciudad USING btree (ciudad_id);


--
-- Name: personas_paisciudad_pais_id_6d94513b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_paisciudad_pais_id_6d94513b ON public.personas_paisciudad USING btree (pais_id);


--
-- Name: personas_persona_cedula_3656fca0_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_persona_cedula_3656fca0_like ON public.personas_persona USING btree (cedula varchar_pattern_ops);


--
-- Name: personas_persona_ciudad_nacimiento_id_e4093358; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_persona_ciudad_nacimiento_id_e4093358 ON public.personas_persona USING btree (ciudad_nacimiento_id);


--
-- Name: personas_persona_pais_nacimiento_id_7aec5c11; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_persona_pais_nacimiento_id_7aec5c11 ON public.personas_persona USING btree (pais_nacimiento_id);


--
-- Name: personas_rol_nombre_8a9c7745_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_rol_nombre_8a9c7745_like ON public.personas_rol USING btree (nombre varchar_pattern_ops);


--
-- Name: personas_rolpersona_persona_id_e84f399d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_rolpersona_persona_id_e84f399d ON public.personas_rolpersona USING btree (persona_id);


--
-- Name: personas_rolpersona_rol_id_1bc8bbb6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_rolpersona_rol_id_1bc8bbb6 ON public.personas_rolpersona USING btree (rol_id);


--
-- Name: personas_tiposangre_nombre_89eada6f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_tiposangre_nombre_89eada6f_like ON public.personas_tiposangre USING btree (nombre varchar_pattern_ops);


--
-- Name: personas_tiposangrepersona_persona_id_86d6493d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_tiposangrepersona_persona_id_86d6493d ON public.personas_tiposangrepersona USING btree (persona_id);


--
-- Name: personas_tiposangrepersona_tipo_sangre_id_a622d08b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX personas_tiposangrepersona_tipo_sangre_id_a622d08b ON public.personas_tiposangrepersona USING btree (tipo_sangre_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_cita citas_cita_medico_id_aadcbe06_fk_personas_persona_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_cita
    ADD CONSTRAINT citas_cita_medico_id_aadcbe06_fk_personas_persona_id FOREIGN KEY (medico_id) REFERENCES public.personas_persona(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_cita citas_cita_persona_id_5e7595f8_fk_personas_persona_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_cita
    ADD CONSTRAINT citas_cita_persona_id_5e7595f8_fk_personas_persona_id FOREIGN KEY (persona_id) REFERENCES public.personas_persona(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_citahistorial citas_citahistorial_cita_id_a00066ef_fk_citas_cita_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_citahistorial
    ADD CONSTRAINT citas_citahistorial_cita_id_a00066ef_fk_citas_cita_id FOREIGN KEY (cita_id) REFERENCES public.citas_cita(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_citahistorial citas_citahistorial_usuario_responsable__f8a5605b_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_citahistorial
    ADD CONSTRAINT citas_citahistorial_usuario_responsable__f8a5605b_fk_personas_ FOREIGN KEY (usuario_responsable_id) REFERENCES public.personas_persona(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_antecedente personas_antecedente_historia_clinica_id_4257215b_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_antecedente
    ADD CONSTRAINT personas_antecedente_historia_clinica_id_4257215b_fk_personas_ FOREIGN KEY (historia_clinica_id) REFERENCES public.personas_historiaclinica(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_datosadministrativos personas_datosadmini_historia_clinica_id_ab574e2b_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_datosadministrativos
    ADD CONSTRAINT personas_datosadmini_historia_clinica_id_ab574e2b_fk_personas_ FOREIGN KEY (historia_clinica_id) REFERENCES public.personas_historiaclinica(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_datosadministrativos personas_datosadmini_profesional_id_419644a4_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_datosadministrativos
    ADD CONSTRAINT personas_datosadmini_profesional_id_419644a4_fk_personas_ FOREIGN KEY (profesional_id) REFERENCES public.personas_persona(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_diagnostico personas_diagnostico_historia_clinica_id_6d073200_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_diagnostico
    ADD CONSTRAINT personas_diagnostico_historia_clinica_id_6d073200_fk_personas_ FOREIGN KEY (historia_clinica_id) REFERENCES public.personas_historiaclinica(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_examencomplementario personas_examencompl_historia_clinica_id_7c7baaae_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_examencomplementario
    ADD CONSTRAINT personas_examencompl_historia_clinica_id_7c7baaae_fk_personas_ FOREIGN KEY (historia_clinica_id) REFERENCES public.personas_historiaclinica(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_examenfisico personas_examenfisic_historia_clinica_id_03b399c4_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_examenfisico
    ADD CONSTRAINT personas_examenfisic_historia_clinica_id_03b399c4_fk_personas_ FOREIGN KEY (historia_clinica_id) REFERENCES public.personas_historiaclinica(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_historiaclinica personas_historiacli_autorizado_por_id_bc9a5f95_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_historiaclinica
    ADD CONSTRAINT personas_historiacli_autorizado_por_id_bc9a5f95_fk_personas_ FOREIGN KEY (autorizado_por_id) REFERENCES public.personas_persona(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_historiaclinicapersona personas_historiacli_historia_clinica_id_a4d52dd3_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_historiaclinicapersona
    ADD CONSTRAINT personas_historiacli_historia_clinica_id_a4d52dd3_fk_personas_ FOREIGN KEY (historia_clinica_id) REFERENCES public.personas_historiaclinica(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_historiaclinica personas_historiacli_persona_contacto_id_3d2bb551_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_historiaclinica
    ADD CONSTRAINT personas_historiacli_persona_contacto_id_3d2bb551_fk_personas_ FOREIGN KEY (persona_contacto_id) REFERENCES public.personas_persona(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_historiaclinicapersona personas_historiacli_persona_id_cbdbbd03_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_historiaclinicapersona
    ADD CONSTRAINT personas_historiacli_persona_id_cbdbbd03_fk_personas_ FOREIGN KEY (persona_id) REFERENCES public.personas_persona(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_historiaenfermedadactual personas_historiaenf_historia_clinica_id_6e1521f9_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_historiaenfermedadactual
    ADD CONSTRAINT personas_historiaenf_historia_clinica_id_6e1521f9_fk_personas_ FOREIGN KEY (historia_clinica_id) REFERENCES public.personas_historiaclinica(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_motivoconsulta personas_motivoconsu_historia_clinica_id_2fc0656b_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_motivoconsulta
    ADD CONSTRAINT personas_motivoconsu_historia_clinica_id_2fc0656b_fk_personas_ FOREIGN KEY (historia_clinica_id) REFERENCES public.personas_historiaclinica(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_paisciudad personas_paisciudad_ciudad_id_44c1df30_fk_personas_ciudad_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_paisciudad
    ADD CONSTRAINT personas_paisciudad_ciudad_id_44c1df30_fk_personas_ciudad_id FOREIGN KEY (ciudad_id) REFERENCES public.personas_ciudad(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_paisciudad personas_paisciudad_pais_id_6d94513b_fk_personas_pais_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_paisciudad
    ADD CONSTRAINT personas_paisciudad_pais_id_6d94513b_fk_personas_pais_id FOREIGN KEY (pais_id) REFERENCES public.personas_pais(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_persona personas_persona_ciudad_nacimiento_id_e4093358_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_persona
    ADD CONSTRAINT personas_persona_ciudad_nacimiento_id_e4093358_fk_personas_ FOREIGN KEY (ciudad_nacimiento_id) REFERENCES public.personas_ciudad(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_persona personas_persona_pais_nacimiento_id_7aec5c11_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_persona
    ADD CONSTRAINT personas_persona_pais_nacimiento_id_7aec5c11_fk_personas_ FOREIGN KEY (pais_nacimiento_id) REFERENCES public.personas_pais(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_persona personas_persona_usuario_id_757630d6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_persona
    ADD CONSTRAINT personas_persona_usuario_id_757630d6_fk_auth_user_id FOREIGN KEY (usuario_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_planmanejo personas_planmanejo_historia_clinica_id_95d35b14_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_planmanejo
    ADD CONSTRAINT personas_planmanejo_historia_clinica_id_95d35b14_fk_personas_ FOREIGN KEY (historia_clinica_id) REFERENCES public.personas_historiaclinica(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_rolpersona personas_rolpersona_persona_id_e84f399d_fk_personas_persona_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_rolpersona
    ADD CONSTRAINT personas_rolpersona_persona_id_e84f399d_fk_personas_persona_id FOREIGN KEY (persona_id) REFERENCES public.personas_persona(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_rolpersona personas_rolpersona_rol_id_1bc8bbb6_fk_personas_rol_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_rolpersona
    ADD CONSTRAINT personas_rolpersona_rol_id_1bc8bbb6_fk_personas_rol_id FOREIGN KEY (rol_id) REFERENCES public.personas_rol(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_tiposangrepersona personas_tiposangrep_persona_id_86d6493d_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_tiposangrepersona
    ADD CONSTRAINT personas_tiposangrep_persona_id_86d6493d_fk_personas_ FOREIGN KEY (persona_id) REFERENCES public.personas_persona(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: personas_tiposangrepersona personas_tiposangrep_tipo_sangre_id_a622d08b_fk_personas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_tiposangrepersona
    ADD CONSTRAINT personas_tiposangrep_tipo_sangre_id_a622d08b_fk_personas_ FOREIGN KEY (tipo_sangre_id) REFERENCES public.personas_tiposangre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict eyxS6CYvgGnQEPbB8mCdAei7GWTdCflfrx5smzMl2aEsYwdi7tUCRRojY7vg6P7

